version: '3.8'

services:
  app:
    build: .
    container_name: task_manager-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/taskdb?authSource=admin
      - REDIS_URL=redis://redis-server:6379
      - JWT_SECRET=hhsfjhfjhsfjhwefhj
    depends_on:
      - mongo
      - redis-server
    networks:
      - app-network

  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
