

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/taskdb?authSource=admin
      - REDIS_URL=redis://redis-server:6379  
      - JWT_SECRET=hhsfjhfjhsfjhwefhj
    depends_on:
      - redis-server
      - mongo

  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"  # Redis ka port map kiya gaya hai

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # MongoDB ka port map kiya gaya hai
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
